name: 申请加入 Ponder
description: 填写订单号申请加入 Ponder
title: "[申请Ponder] "
body:
  - type: input
    id: order_no
    attributes:
      label: 订单号
      description: 请填写你的订单号（如 P101）
      placeholder: P101
    validations:
      required: true
